# Site settings
title: A Developing Story
header-img: img/home-bg.png
email: rlmandelbaum@gmail.com
copyright_name: RMandelbaum
description: > # this means to ignore newlines until "baseurl:"
  Learning to Code, One Error at a Time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  RMandelbaum
learn_profile: RMandelbaum
email_username: rlmandelbaum@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
